---
title: Programming Over Time
description: "Let's explore software engineering!"
date: 2024-09-02
layout: full
toc: true
toc-expand: 3
published-title: "Starting Date"
---

## Week Two

### Monday, September 2 -- Friday, September 6

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - {{< iconify fa-regular sad-tear size=19px >}} No class, discussion to occur on Wednesday
  - *Discussion leads facilitate the discussion of a published executive summary*:
    - **Team-Based Discussion of SE1**: Preface - Programming Over Time
    - **Preparation for SE2**: What is Software Engineering?

- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discussion leads facilitate the discussion of a published executive summary*:
    - {{< iconify fa-regular sad-tear size=19px >}} Due to no class on Monday, discussion moved to the lab session
    - **Team-based Discussion of FB1**: Introduction to Software Testing
    - **Preparation for FB2**: Code Coverage
- {{< iconify fa6-solid diagram-project size=18px >}} **Thursday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Explore the use of the software tools subject to development
    - Elicit requirements for the software tools subject to development
    - Create issues in the issue tracker to describe new features
    - Assign tasks to each team member
    - Set deadlines for the completion of the tasks
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE2**: What is Software Engineering?
        - **Publication of FB2**: Code Coverage
    - *Confirm that all team members can use the following tools*:
      - GitHub and GitHub Flow
      - Python, Poetry, and Pipx
      - VSCode and Python programming tools
      - VSCode and the Quarto publishing tool
      - Demonstrate the use of the software tools subject to development
