---
title: "Schedule"
toc: true
page-layout: full
---

## Preliminaries

### Schedule Overview

- **Week One**: Technical and Professional Onboarding
- **Module One**: *Introduction to Software Engineering Knowledge and Skills*
    - **Week Two through Week Five**: Establish your technical and professional skills
    - **Week Six**:
      - **Monday**: in-person assessment of individual developer development
      - **Tuesday**: take the first executable examination during laboratory session
      - **Wednesday**: in-person assessment of individual developer development
      - **Friday**:  in-person assessment of individual developer development
- **Module Two**: *Practical Software Engineering Knowledge and Skills*
    - **Week Seven through Week Ten**: Enhance your technical and professional skills
    - **Week Six**:
      - **Monday**: in-person assessment of individual developer development
      - **Tuesday**: take the second first executable examination during laboratory session
      - **Wednesday**: in-person assessment of individual developer development
      - **Friday**:  in-person assessment of individual developer development

### Weekly Cadence

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - Team-based discussion of prior week's reading in SE
    - Focused individual preparation for next week's SE reading
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Sprint planning
    - Project implementation
    - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - Team-based discussion of prior week's reading in either FB or DB
    - Focused individual preparation for next week's FB or DB reading
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - Publication of next SE executive summary
        - Publication of next FB or DB executive summary
        - Confirmation of readiness for next week's in-class discussions

### Project Deadlines

- Project One: Chasten tool for automated analysis of Python projects
    - **Week One**: Onboarding of team members
    - **Week Two**: Official start for first project
    - **Week Eight**: Chasten completion and project maintenance
    - **Week Nine**: Final demonstration of the Chasten tool
- Project Two: Astronaught tool for deletion mutation analysis of Python projects
    - **Week Eight**: Onboarding of team members
    - **Week Nine**: Official start for second project
    - **Week Fifteen**: Astronaught completion and project maintenance
    - **Week Sixteen**: Final demonstration of the Astronaught tool

::: {.callout-note appearance="minimal" title="Abbreviations" collapse="false"}

- SE: [Software Engineering at Google](https://abseil.io/resources/swe-book)
- FB: [Fuzzing Book](https://www.fuzzingbook.org/)
- DB: [Debugging Book](https://www.debuggingbook.org/)

:::

## Week One

### Tuesday, August 29 -- Friday, September 1

- {{< iconify fa-regular sad-tear size=19px >}} **Monday**: No class
- {{< iconify fa-solid laptop-code size=18px >}} **Tuesday**: Technical preparation for joining a software startup
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical preparation for joining a software startup
- {{< iconify fa-solid laptop-code size=18px >}} **Friday**: Technical and professional preparation for joining a software startup

::: {.callout-note appearance="minimal" title="Onboarding Tasks" collapse="false"}

- Join the [Developer Development Discord](https://discord.gg/aNfn8DNEMx)
- Install [Python 3.11](https://www.python.org/) on your development workstation
    - Use [asdf-vm](https://asdf-vm.com/) or [rtx](https://github.com/jdx/rtx) to install Python on MacOS or Linux
    - Use [asdf-vm](https://asdf-vm.com/more/faq.html#wsl2-support) on Windows with WSL2 support
    - Use the official [installers](https://www.python.org/downloads/) for Windows 10 or Windows 11
    - Install the full Python version supporting C and Rust binding and SQLite 3
- Install the [Poetry](https://python-poetry.org/) and [Pipx](https://github.com/pypa/pipx) tools to support Python development
- Access both the [Fuzzing Book (FB)](https://www.fuzzingbook.org/) and the [Debugging Book (DB)](https://www.debuggingbook.org/)
    - Fork the GitHub repositories for these two books
    - Clone the forked GitHub repositories to your workstation
    - Use `pip` to install each books' dependencies
    - Run a local Jupyter Lab server that can access a book's Jupyter notebooks
    - Correctly run the Jupyter notebook for at least one chapter in FB or DB
- Locate and bookmark the [Software Engineering at Google](https://abseil.io/resources/swe-book) book
- Install the [Quarto](https://quarto.org/) system for scientific and technical publishing
- Learn how to use [Quarto](https://quarto.org/) to create a [web site](https://quarto.org/docs/websites/)
- Install and learn how to use the [Chasten](https://github.com/AstuteSource/chasten) tool for analyzing Python ASTs
- Raise issues in the [Chasten issue tracker](https://github.com/AstuteSource/chasten/issues) for any problems you encounter
- Attach labels to all issues in the [Chasten issue tracker](https://github.com/AstuteSource/chasten/issues)

:::

## Week Two

### Monday, September 4 -- Friday, September 8

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Write a professional précis and publish the team's executive summary*:
    - **Preparation for SE1**: Preface - Programming Over Time
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Demonstrate installation and use of the following artifacts:
        - [Chasten](https://github.com/AstuteSource/chasten): tool for analyzing Python abstract syntax trees
        - [Fuzzing Book (FB)](https://www.fuzzingbook.org/): tools and techniques for generating tests
        - [Debugging Book (DB)](https://www.debuggingbook.org/): tools and techniques for automated debugging
    - Label all of the issues in the [Chasten issue tracker](https://github.com/AstuteSource/chasten/issues)
    - Assign team members to all of the issues in the [Chasten issue tracker](https://github.com/AstuteSource/chasten/issues)
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
    - *Write a professional précis and publish the team's executive summary*:
        - **Preparation for FB1**: Introduction to Software Testing
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE1**: Preface - Programming Over Time
        - **Publication of FB1**: Introduction to Software Testing

## Week Three

### Monday, September 11 -- Friday, September 15

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of SE1**: Preface - Programming Over Time
    - **Preparation for SE2**: What is Software Engineering?
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Sprint planning
    - Project implementation
    - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of FB1**: Introduction to Software Testing
    - **Preparation for FB2**: Coverage
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE2**: What is Software Engineering?
        - **Publication of FB2**: Coverage

## Week Four

### Monday, September 18 -- Friday, September 22

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of SE2**: What is Software Engineering?
    - **Preparation for SE3**: How to Work Well on Teams
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Sprint planning
    - Project implementation
    - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of FB2**: Coverage
    - **Preparation for FB3**: Fuzzing
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE3**: How to Work Well on Teams
        - **Publication of FB3**: Fuzzing

## Week Five

### Monday, September 25 -- Friday, September 29

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of SE3**: How to Work Well on Teams
    - **Preparation for SE4**: Knowledge Sharing
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Sprint planning
    - Project implementation
    - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of FB3**: Fuzzing
    - **Preparation for FB4**: Mutation Analysis
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE4**: Knowledge Sharing
        - **Publication of FB4**: Mutation Analysis

## Week Six

### Monday, October 2 -- Friday, October 6

- {{< iconify fa6-solid list-check size=18px >}} **Monday, Wednesday, and Friday**: People Operations
  - *In-person technical and professional assessment of all student team members*:
    - {{< iconify fa6-solid people-line size=18px >}} Answer at least one question about professional skills
    - {{< iconify fa-solid laptop-code size=18px >}} Answer at least one question about technical skills
    - {{< iconify fa6-solid diagram-project size=18px >}} Answer at least one technical question about the project
    - {{< iconify game-icons team-idea size=18px >}} Document professional insights in an assessment report

- {{< iconify fa6-solid flag-checkered size=18px >}} **Tuesday**: Executable Examination
  - *Demonstrate technical skills in software engineering*:
    - Use GitHub and GitHub Actions
    - Use text editor and terminal window
    - Implement and test Python functions
    - Debug defective Python functions
    - Confirm output of Python functions

::: {.callout-note appearance="minimal" title="Assessment Reminder" collapse="false"}

Both the in-person assessment and the executable examination are cumulative in
regards to all content previously covered between week one and week five.

:::

## Week Seven

### Monday, October 9 -- Friday, October 13

- {{< iconify fa-regular sad-tear size=19px >}} **Monday**: No class
- {{< iconify fa-regular sad-tear size=19px >}} **Tuesday**: No class
- {{< iconify fa6-solid people-line size=18px >}} **Wednesday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Discussion of SE4**: Knowledge Sharing
    - **Publication of SE5**: Engineering for Equity
- {{< iconify fa-solid laptop-code size=18px >}} **Friday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Discussion of FB4**: Mutation Analysis
    - **Publication of FB5**: Mutation-Based Fuzzing

## Week Eight

### Monday, October 16 -- Friday, October 20

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of SE5**: How to Work Well on Teams
    - **Preparation for SE6**: How to Lead a Team
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - First software tool enters maintenance mode
    - Begin to focus on the second software tool
        - Sprint planning
        - Project implementation
        - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of FB5**: Mutation-Based Fuzzing
    - **Preparation for FB6**: Fuzzing with Grammars
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE6**: How to Lead a Team
        - **Publication of FB6**: Fuzzing with Grammars

## Week Nine

### Monday, October 23 -- Friday, October 27

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of SE6**: How to Lead a Team
    - **Preparation for SE7**: Leading at Scale
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Demonstration of completed version of the first software tool
    - Development of the second software tool
        - Sprint planning
        - Project implementation
        - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of FB6**: Fuzzing with Grammars
    - **Preparation for FB7**: Efficient Grammar Fuzzing
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE7**: Leading at Scale
        - **Publication of FB6**: Efficient Grammar Fuzzing

## Week Ten

### Monday, October 30 -- Friday, November 3

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of SE7**: Leading at Scale
    - **Preparation for SE8**: Style Guides and Rules
- {{< iconify fa6-solid diagram-project size=18px >}} **Tuesday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Sprint planning
    - Project implementation
    - Project demonstration
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discuss the team's executive summary and write a professional précis*:
    - **Team-based Discussion of FB7**: Efficient Grammar Fuzzing
    - **Preparation for FB8**: Parsing Inputs
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE8**: Style Guides and Rules
        - **Publication of FB8**: Parsing Inputs

## Week Eleven

### Monday, November 6 -- Friday, November 10

- {{< iconify fa6-solid list-check size=18px >}} **Monday, Wednesday, and Friday**: People Operations
  - *In-person technical and professional assessment of all student team members*:
    - {{< iconify fa6-solid people-line size=18px >}} Answer at least one question about professional skills
    - {{< iconify fa-solid laptop-code size=18px >}} Answer at least one question about technical skills
    - {{< iconify fa6-solid diagram-project size=18px >}} Answer at least one technical question about the project
    - {{< iconify game-icons team-idea size=18px >}} Document professional insights in an assessment report

- {{< iconify fa6-solid flag-checkered size=18px >}} **Tuesday**: Executable Examination
  - *Demonstrate technical skills in software engineering*:
    - Use GitHub and GitHub Actions
    - Use text editor and terminal window
    - Implement and test Python functions
    - Debug defective Python functions
    - Confirm output of Python functions

::: {.callout-note appearance="minimal" title="Assessment Reminder" collapse="false"}

Both the in-person assessment and the executable examination are cumulative in
regards to all content previously covered between week one and week eleven.

:::
