---
title: Effective Teamwork
description: "How can we effectively work together as engineers?"
date: 2024-09-16
layout: full
toc: true
toc-expand: 3
published-title: "Starting Date"
---

## Week Four

### Monday, September 16 -- Friday, September 20

- {{< iconify fa6-solid people-line size=18px >}} **Monday**: Professional Development
  - *Discussion leads facilitate the discussion of a published executive summary*:
    - **Team-based Discussion of SE3**: How to Work Well on Teams
    - **Preparation for SE4**: Knowledge Sharing
- {{< iconify fa-solid laptop-code size=18px >}} **Wednesday**: Technical Development
  - *Discussion leads facilitate the discussion of a published executive summary*:
    - **Team-Based Discussion of FB3**: Fuzzing: Breaking Things with Random Inputs
    - **Preparation for FB4**: Mutation Analysis
- {{< iconify fa6-solid diagram-project size=18px >}} **Thursday**: Project Development
  - *Collaboratively implement and deploy into production a software tool*:
    - Explore the use of the software tools subject to development
    - Elicit requirements for the software tools subject to development
    - Create issues in the issue tracker to describe new features
    - Assign tasks to each team member
    - Set deadlines for the completion of the tasks
- {{< iconify game-icons team-idea size=18px >}} **Friday**: Developer Development
    - *Publish executive summaries to the Developer Development blog*:
        - **Publication of SE4**: Knowledge Sharing
        - **Publication of FB4**: Mutation Analysis
    - *Software Engineering Checkup*:
      - Demonstrate the following software tools:
        - GatorGrade
        - GatorGrader
        - ExecExam
      - Each team member must:
        - Demonstrate at least one feature in one software tool
        - Show that they have an effective engineering tool setup
        - Share their plan for continued progress on their features
